// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: re/oracle/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1ddf340e30c129b, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1ddf340e30c129b, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetMultiChainTxOracleRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetMultiChainTxOracleRequest) Reset()         { *m = QueryGetMultiChainTxOracleRequest{} }
func (m *QueryGetMultiChainTxOracleRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetMultiChainTxOracleRequest) ProtoMessage()    {}
func (*QueryGetMultiChainTxOracleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1ddf340e30c129b, []int{2}
}
func (m *QueryGetMultiChainTxOracleRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMultiChainTxOracleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMultiChainTxOracleRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMultiChainTxOracleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMultiChainTxOracleRequest.Merge(m, src)
}
func (m *QueryGetMultiChainTxOracleRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMultiChainTxOracleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMultiChainTxOracleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMultiChainTxOracleRequest proto.InternalMessageInfo

func (m *QueryGetMultiChainTxOracleRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetMultiChainTxOracleResponse struct {
	MultiChainTxOracle MultiChainTxOracle `protobuf:"bytes,1,opt,name=MultiChainTxOracle,proto3" json:"MultiChainTxOracle"`
}

func (m *QueryGetMultiChainTxOracleResponse) Reset()         { *m = QueryGetMultiChainTxOracleResponse{} }
func (m *QueryGetMultiChainTxOracleResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetMultiChainTxOracleResponse) ProtoMessage()    {}
func (*QueryGetMultiChainTxOracleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1ddf340e30c129b, []int{3}
}
func (m *QueryGetMultiChainTxOracleResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMultiChainTxOracleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMultiChainTxOracleResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMultiChainTxOracleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMultiChainTxOracleResponse.Merge(m, src)
}
func (m *QueryGetMultiChainTxOracleResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMultiChainTxOracleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMultiChainTxOracleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMultiChainTxOracleResponse proto.InternalMessageInfo

func (m *QueryGetMultiChainTxOracleResponse) GetMultiChainTxOracle() MultiChainTxOracle {
	if m != nil {
		return m.MultiChainTxOracle
	}
	return MultiChainTxOracle{}
}

type QueryAllMultiChainTxOracleRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllMultiChainTxOracleRequest) Reset()         { *m = QueryAllMultiChainTxOracleRequest{} }
func (m *QueryAllMultiChainTxOracleRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllMultiChainTxOracleRequest) ProtoMessage()    {}
func (*QueryAllMultiChainTxOracleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1ddf340e30c129b, []int{4}
}
func (m *QueryAllMultiChainTxOracleRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllMultiChainTxOracleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllMultiChainTxOracleRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllMultiChainTxOracleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllMultiChainTxOracleRequest.Merge(m, src)
}
func (m *QueryAllMultiChainTxOracleRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllMultiChainTxOracleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllMultiChainTxOracleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllMultiChainTxOracleRequest proto.InternalMessageInfo

func (m *QueryAllMultiChainTxOracleRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllMultiChainTxOracleResponse struct {
	MultiChainTxOracle []MultiChainTxOracle `protobuf:"bytes,1,rep,name=MultiChainTxOracle,proto3" json:"MultiChainTxOracle"`
	Pagination         *query.PageResponse  `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllMultiChainTxOracleResponse) Reset()         { *m = QueryAllMultiChainTxOracleResponse{} }
func (m *QueryAllMultiChainTxOracleResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllMultiChainTxOracleResponse) ProtoMessage()    {}
func (*QueryAllMultiChainTxOracleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1ddf340e30c129b, []int{5}
}
func (m *QueryAllMultiChainTxOracleResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllMultiChainTxOracleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllMultiChainTxOracleResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllMultiChainTxOracleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllMultiChainTxOracleResponse.Merge(m, src)
}
func (m *QueryAllMultiChainTxOracleResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllMultiChainTxOracleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllMultiChainTxOracleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllMultiChainTxOracleResponse proto.InternalMessageInfo

func (m *QueryAllMultiChainTxOracleResponse) GetMultiChainTxOracle() []MultiChainTxOracle {
	if m != nil {
		return m.MultiChainTxOracle
	}
	return nil
}

func (m *QueryAllMultiChainTxOracleResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "jim380.re.oracle.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "jim380.re.oracle.QueryParamsResponse")
	proto.RegisterType((*QueryGetMultiChainTxOracleRequest)(nil), "jim380.re.oracle.QueryGetMultiChainTxOracleRequest")
	proto.RegisterType((*QueryGetMultiChainTxOracleResponse)(nil), "jim380.re.oracle.QueryGetMultiChainTxOracleResponse")
	proto.RegisterType((*QueryAllMultiChainTxOracleRequest)(nil), "jim380.re.oracle.QueryAllMultiChainTxOracleRequest")
	proto.RegisterType((*QueryAllMultiChainTxOracleResponse)(nil), "jim380.re.oracle.QueryAllMultiChainTxOracleResponse")
}

func init() { proto.RegisterFile("re/oracle/query.proto", fileDescriptor_e1ddf340e30c129b) }

var fileDescriptor_e1ddf340e30c129b = []byte{
	// 512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xc1, 0x6a, 0x13, 0x41,
	0x18, 0xc7, 0x33, 0x69, 0xcd, 0x61, 0x04, 0x91, 0xb1, 0x95, 0xb0, 0xc8, 0x5a, 0x47, 0x6b, 0x55,
	0x64, 0xc6, 0x36, 0x45, 0xbc, 0x78, 0x68, 0x05, 0x7b, 0x2a, 0xd6, 0xc5, 0x53, 0x2f, 0x61, 0x92,
	0x0c, 0xdb, 0xd1, 0xdd, 0x9d, 0xed, 0xce, 0x44, 0x53, 0x44, 0x10, 0x9f, 0x40, 0xf0, 0x51, 0xc4,
	0x77, 0xa8, 0xb7, 0x82, 0x17, 0x4f, 0x22, 0x89, 0x67, 0x9f, 0x41, 0x76, 0x66, 0x42, 0xd2, 0x6c,
	0x76, 0xa3, 0x78, 0x0b, 0x33, 0xff, 0xef, 0xff, 0xfd, 0xfe, 0xf9, 0xbe, 0x59, 0xb8, 0x9a, 0x71,
	0x2a, 0x33, 0xd6, 0x8d, 0x38, 0x3d, 0xee, 0xf3, 0xec, 0x84, 0xa4, 0x99, 0xd4, 0x12, 0x5d, 0x7e,
	0x29, 0xe2, 0xd6, 0xa3, 0x07, 0x24, 0xe3, 0xc4, 0xde, 0x7a, 0x2b, 0xa1, 0x0c, 0xa5, 0xb9, 0xa4,
	0xf9, 0x2f, 0xab, 0xf3, 0xae, 0x85, 0x52, 0x86, 0x11, 0xa7, 0x2c, 0x15, 0x94, 0x25, 0x89, 0xd4,
	0x4c, 0x0b, 0x99, 0x28, 0x77, 0x7b, 0xaf, 0x2b, 0x55, 0x2c, 0x15, 0xed, 0x30, 0xe5, 0xec, 0xe9,
	0xeb, 0xcd, 0x0e, 0xd7, 0x6c, 0x93, 0xa6, 0x2c, 0x14, 0x89, 0x11, 0x3b, 0xed, 0xd5, 0x09, 0x48,
	0xca, 0x32, 0x16, 0x8f, 0x3d, 0xd6, 0x27, 0xe7, 0x71, 0x3f, 0xd2, 0xa2, 0xdd, 0x3d, 0x62, 0x22,
	0x69, 0xeb, 0x41, 0xdb, 0x9e, 0x5a, 0x19, 0x5e, 0x81, 0xe8, 0x79, 0xde, 0xe0, 0xc0, 0xd4, 0x06,
	0xfc, 0xb8, 0xcf, 0x95, 0xc6, 0xfb, 0xf0, 0xca, 0xb9, 0x53, 0x95, 0xca, 0x44, 0x71, 0xf4, 0x10,
	0x36, 0x6c, 0x8f, 0x26, 0x58, 0x03, 0x77, 0x2e, 0x6e, 0x35, 0xc9, 0x6c, 0x5c, 0x62, 0x2b, 0x76,
	0x97, 0x4f, 0x7f, 0x5c, 0xaf, 0x05, 0x4e, 0x8d, 0x5b, 0xf0, 0x86, 0xb1, 0xdb, 0xe3, 0x7a, 0x3f,
	0x67, 0x79, 0x92, 0xa3, 0xbc, 0x18, 0x3c, 0x33, 0x25, 0xae, 0x27, 0xba, 0x04, 0xeb, 0xa2, 0x67,
	0x8c, 0x97, 0x83, 0xba, 0xe8, 0xe1, 0xf7, 0x00, 0xe2, 0xaa, 0x2a, 0xc7, 0x74, 0x08, 0x51, 0xf1,
	0xd6, 0xf1, 0xdd, 0x2a, 0xf2, 0x15, 0xb5, 0x8e, 0x75, 0x8e, 0x0b, 0x7e, 0xe5, 0xb8, 0x77, 0xa2,
	0xa8, 0x9c, 0xfb, 0x29, 0x84, 0x93, 0xa1, 0xb8, 0xc6, 0xb7, 0x89, 0x9d, 0x20, 0xc9, 0x27, 0x48,
	0xec, 0x82, 0xb8, 0x09, 0x92, 0x03, 0x16, 0x8e, 0x6b, 0x83, 0xa9, 0x4a, 0xfc, 0x75, 0x9c, 0xb7,
	0xa4, 0xdb, 0x82, 0xbc, 0x4b, 0xff, 0x9f, 0x17, 0xed, 0x9d, 0x8b, 0x52, 0x37, 0x51, 0x36, 0x16,
	0x46, 0xb1, 0x60, 0xd3, 0x59, 0xb6, 0x7e, 0x2f, 0xc1, 0x0b, 0x26, 0x0b, 0x7a, 0x03, 0x1b, 0x76,
	0x25, 0xd0, 0x1c, 0xb8, 0xe2, 0xe6, 0x79, 0xeb, 0x0b, 0x54, 0xb6, 0x19, 0x5e, 0xfb, 0xf0, 0xed,
	0xd7, 0xa7, 0xba, 0x87, 0x9a, 0xd4, 0xca, 0x69, 0x30, 0xf3, 0x0a, 0xd0, 0x17, 0x30, 0xef, 0x8f,
	0x42, 0xad, 0x12, 0xff, 0xaa, 0xd5, 0xf4, 0xb6, 0xff, 0xad, 0xc8, 0x31, 0x6e, 0x1b, 0x46, 0x82,
	0xee, 0x17, 0x19, 0xe7, 0xbe, 0x48, 0xfa, 0x56, 0xf4, 0xde, 0xa1, 0xcf, 0x00, 0xae, 0x16, 0x4d,
	0x77, 0xa2, 0xa8, 0x14, 0xbd, 0x6a, 0x3b, 0x4b, 0xd1, 0x2b, 0x97, 0x0c, 0x53, 0x83, 0x7e, 0x17,
	0x6d, 0xfc, 0x25, 0xfa, 0xee, 0xe3, 0xd3, 0xa1, 0x0f, 0xce, 0x86, 0x3e, 0xf8, 0x39, 0xf4, 0xc1,
	0xc7, 0x91, 0x5f, 0x3b, 0x1b, 0xf9, 0xb5, 0xef, 0x23, 0xbf, 0x76, 0x78, 0x33, 0x14, 0xfa, 0xa8,
	0xdf, 0x21, 0x5d, 0x19, 0x4f, 0x99, 0x0d, 0xc6, 0x76, 0xfa, 0x24, 0xe5, 0xaa, 0xd3, 0x30, 0x1f,
	0xa3, 0xd6, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x31, 0xdf, 0xfc, 0xc2, 0x56, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of MultiChainTxOracle items.
	MultiChainTxOracle(ctx context.Context, in *QueryGetMultiChainTxOracleRequest, opts ...grpc.CallOption) (*QueryGetMultiChainTxOracleResponse, error)
	MultiChainTxOracleAll(ctx context.Context, in *QueryAllMultiChainTxOracleRequest, opts ...grpc.CallOption) (*QueryAllMultiChainTxOracleResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/jim380.re.oracle.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MultiChainTxOracle(ctx context.Context, in *QueryGetMultiChainTxOracleRequest, opts ...grpc.CallOption) (*QueryGetMultiChainTxOracleResponse, error) {
	out := new(QueryGetMultiChainTxOracleResponse)
	err := c.cc.Invoke(ctx, "/jim380.re.oracle.Query/MultiChainTxOracle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MultiChainTxOracleAll(ctx context.Context, in *QueryAllMultiChainTxOracleRequest, opts ...grpc.CallOption) (*QueryAllMultiChainTxOracleResponse, error) {
	out := new(QueryAllMultiChainTxOracleResponse)
	err := c.cc.Invoke(ctx, "/jim380.re.oracle.Query/MultiChainTxOracleAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of MultiChainTxOracle items.
	MultiChainTxOracle(context.Context, *QueryGetMultiChainTxOracleRequest) (*QueryGetMultiChainTxOracleResponse, error)
	MultiChainTxOracleAll(context.Context, *QueryAllMultiChainTxOracleRequest) (*QueryAllMultiChainTxOracleResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) MultiChainTxOracle(ctx context.Context, req *QueryGetMultiChainTxOracleRequest) (*QueryGetMultiChainTxOracleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiChainTxOracle not implemented")
}
func (*UnimplementedQueryServer) MultiChainTxOracleAll(ctx context.Context, req *QueryAllMultiChainTxOracleRequest) (*QueryAllMultiChainTxOracleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiChainTxOracleAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jim380.re.oracle.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MultiChainTxOracle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetMultiChainTxOracleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MultiChainTxOracle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jim380.re.oracle.Query/MultiChainTxOracle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MultiChainTxOracle(ctx, req.(*QueryGetMultiChainTxOracleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MultiChainTxOracleAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllMultiChainTxOracleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MultiChainTxOracleAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jim380.re.oracle.Query/MultiChainTxOracleAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MultiChainTxOracleAll(ctx, req.(*QueryAllMultiChainTxOracleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "jim380.re.oracle.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "MultiChainTxOracle",
			Handler:    _Query_MultiChainTxOracle_Handler,
		},
		{
			MethodName: "MultiChainTxOracleAll",
			Handler:    _Query_MultiChainTxOracleAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "re/oracle/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetMultiChainTxOracleRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMultiChainTxOracleRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMultiChainTxOracleRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetMultiChainTxOracleResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMultiChainTxOracleResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMultiChainTxOracleResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MultiChainTxOracle.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllMultiChainTxOracleRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllMultiChainTxOracleRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllMultiChainTxOracleRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllMultiChainTxOracleResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllMultiChainTxOracleResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllMultiChainTxOracleResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.MultiChainTxOracle) > 0 {
		for iNdEx := len(m.MultiChainTxOracle) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MultiChainTxOracle[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetMultiChainTxOracleRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetMultiChainTxOracleResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MultiChainTxOracle.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllMultiChainTxOracleRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllMultiChainTxOracleResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MultiChainTxOracle) > 0 {
		for _, e := range m.MultiChainTxOracle {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMultiChainTxOracleRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMultiChainTxOracleRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMultiChainTxOracleRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMultiChainTxOracleResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMultiChainTxOracleResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMultiChainTxOracleResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MultiChainTxOracle", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MultiChainTxOracle.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllMultiChainTxOracleRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllMultiChainTxOracleRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllMultiChainTxOracleRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllMultiChainTxOracleResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllMultiChainTxOracleResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllMultiChainTxOracleResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MultiChainTxOracle", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MultiChainTxOracle = append(m.MultiChainTxOracle, MultiChainTxOracle{})
			if err := m.MultiChainTxOracle[len(m.MultiChainTxOracle)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
