name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, labeled]

permissions:
  contents: read
  repository-projects: read
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  golangci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.60.0
          args: --timeout 10m --tests=false --out-format=github-actions
          skip-pkg-cache: true
  # TO-DO: Re-enable once fixed locally
  # protobuf:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Install Buf
  #       uses: bufbuild/buf-setup-action@v1.26.1
  #     - name: Lint Proto
  #       run: make proto-lint
  #     - name: clang-format Check
  #       uses: jidicula/clang-format-action@v4.11.0
  #       with:
  #         clang-format-version: 17
  #         extensions: proto
  #         file: proto
  #         style: file
