// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: re/fix/market_data.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MarketData struct {
	SessionID         string             `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	MarketDataRequest *MarketDataRequest `protobuf:"bytes,2,opt,name=marketDataRequest,proto3" json:"marketDataRequest,omitempty"`
}

func (m *MarketData) Reset()         { *m = MarketData{} }
func (m *MarketData) String() string { return proto.CompactTextString(m) }
func (*MarketData) ProtoMessage()    {}
func (*MarketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_774f86e03def608c, []int{0}
}
func (m *MarketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MarketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MarketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MarketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketData.Merge(m, src)
}
func (m *MarketData) XXX_Size() int {
	return m.Size()
}
func (m *MarketData) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketData.DiscardUnknown(m)
}

var xxx_messageInfo_MarketData proto.InternalMessageInfo

func (m *MarketData) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *MarketData) GetMarketDataRequest() *MarketDataRequest {
	if m != nil {
		return m.MarketDataRequest
	}
	return nil
}

type MarketDataRequest struct {
	Header                  *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	MdReqID                 string   `protobuf:"bytes,2,opt,name=mdReqID,proto3" json:"mdReqID,omitempty"`
	SubscriptionRequestType int32    `protobuf:"varint,3,opt,name=subscriptionRequestType,proto3" json:"subscriptionRequestType,omitempty"`
	MarketDepth             int32    `protobuf:"varint,4,opt,name=marketDepth,proto3" json:"marketDepth,omitempty"`
	MdUpdateType            int32    `protobuf:"varint,5,opt,name=mdUpdateType,proto3" json:"mdUpdateType,omitempty"`
	NoRelatedSym            int32    `protobuf:"varint,6,opt,name=noRelatedSym,proto3" json:"noRelatedSym,omitempty"`
	Symbol                  string   `protobuf:"bytes,7,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Mic                     string   `protobuf:"bytes,8,opt,name=mic,proto3" json:"mic,omitempty"`
	Trailer                 *Trailer `protobuf:"bytes,9,opt,name=trailer,proto3" json:"trailer,omitempty"`
	Creator                 string   `protobuf:"bytes,10,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *MarketDataRequest) Reset()         { *m = MarketDataRequest{} }
func (m *MarketDataRequest) String() string { return proto.CompactTextString(m) }
func (*MarketDataRequest) ProtoMessage()    {}
func (*MarketDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_774f86e03def608c, []int{1}
}
func (m *MarketDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MarketDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MarketDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MarketDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketDataRequest.Merge(m, src)
}
func (m *MarketDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *MarketDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MarketDataRequest proto.InternalMessageInfo

func (m *MarketDataRequest) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MarketDataRequest) GetMdReqID() string {
	if m != nil {
		return m.MdReqID
	}
	return ""
}

func (m *MarketDataRequest) GetSubscriptionRequestType() int32 {
	if m != nil {
		return m.SubscriptionRequestType
	}
	return 0
}

func (m *MarketDataRequest) GetMarketDepth() int32 {
	if m != nil {
		return m.MarketDepth
	}
	return 0
}

func (m *MarketDataRequest) GetMdUpdateType() int32 {
	if m != nil {
		return m.MdUpdateType
	}
	return 0
}

func (m *MarketDataRequest) GetNoRelatedSym() int32 {
	if m != nil {
		return m.NoRelatedSym
	}
	return 0
}

func (m *MarketDataRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *MarketDataRequest) GetMic() string {
	if m != nil {
		return m.Mic
	}
	return ""
}

func (m *MarketDataRequest) GetTrailer() *Trailer {
	if m != nil {
		return m.Trailer
	}
	return nil
}

func (m *MarketDataRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*MarketData)(nil), "jim380.re.fix.MarketData")
	proto.RegisterType((*MarketDataRequest)(nil), "jim380.re.fix.MarketDataRequest")
}

func init() { proto.RegisterFile("re/fix/market_data.proto", fileDescriptor_774f86e03def608c) }

var fileDescriptor_774f86e03def608c = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x3f, 0xaf, 0xd3, 0x30,
	0x14, 0xc5, 0x9b, 0xf7, 0x78, 0x29, 0x71, 0x41, 0xe2, 0x59, 0xe2, 0x61, 0x21, 0x88, 0xa2, 0x4e,
	0x5d, 0x48, 0xaa, 0x76, 0xa9, 0x18, 0x51, 0x07, 0x3a, 0x94, 0xc1, 0x94, 0x85, 0xa5, 0x72, 0xe2,
	0xdb, 0xd6, 0x50, 0xc7, 0xa9, 0xed, 0x4a, 0x0d, 0x9f, 0x82, 0x8f, 0xc5, 0xd8, 0x91, 0x11, 0xb5,
	0xdf, 0x81, 0x19, 0xd5, 0x49, 0xa1, 0x7f, 0xc4, 0x96, 0x7b, 0xee, 0x2f, 0xc7, 0x47, 0x47, 0x17,
	0x11, 0x0d, 0xc9, 0x4c, 0x6c, 0x12, 0xc9, 0xf4, 0x57, 0xb0, 0x53, 0xce, 0x2c, 0x8b, 0x0b, 0xad,
	0xac, 0xc2, 0x4f, 0xbf, 0x08, 0xd9, 0x1f, 0x74, 0x63, 0x0d, 0xf1, 0x4c, 0x6c, 0x5e, 0xbe, 0xae,
	0x41, 0x63, 0x59, 0xce, 0x99, 0xe6, 0x53, 0x09, 0xc6, 0xb0, 0x39, 0x54, 0x74, 0xfb, 0x1b, 0x42,
	0x63, 0x67, 0x31, 0x64, 0x96, 0xe1, 0x57, 0x28, 0x30, 0x60, 0x8c, 0x50, 0xf9, 0x68, 0x48, 0xbc,
	0xc8, 0xeb, 0x04, 0xf4, 0x9f, 0x80, 0x3f, 0xa0, 0x7b, 0xf9, 0x97, 0xa5, 0xb0, 0x5a, 0x83, 0xb1,
	0xe4, 0x26, 0xf2, 0x3a, 0xad, 0x5e, 0x14, 0x9f, 0xbd, 0x1a, 0x8f, 0x2f, 0x39, 0x7a, 0xfd, 0x6b,
	0xfb, 0xf7, 0x0d, 0xba, 0xbf, 0x02, 0xf1, 0x1b, 0xe4, 0x2f, 0x80, 0x71, 0xd0, 0x2e, 0x40, 0xab,
	0xf7, 0xfc, 0xc2, 0xfa, 0xbd, 0x5b, 0xd2, 0x1a, 0xc2, 0x04, 0x35, 0x25, 0xa7, 0xb0, 0x1a, 0x0d,
	0x5d, 0x94, 0x80, 0x1e, 0x47, 0x3c, 0x40, 0x2f, 0xcc, 0x3a, 0x35, 0x99, 0x16, 0x85, 0x15, 0x2a,
	0xaf, 0xfd, 0x27, 0x65, 0x01, 0xe4, 0x36, 0xf2, 0x3a, 0x77, 0xf4, 0x7f, 0x6b, 0x1c, 0xa1, 0x56,
	0x9d, 0x16, 0x0a, 0xbb, 0x20, 0x8f, 0x1c, 0x7d, 0x2a, 0xe1, 0x36, 0x7a, 0x22, 0xf9, 0xa7, 0x82,
	0x33, 0x0b, 0xce, 0xf0, 0xce, 0x21, 0x67, 0xda, 0x81, 0xc9, 0x15, 0x85, 0x25, 0xb3, 0xc0, 0x3f,
	0x96, 0x92, 0xf8, 0x15, 0x73, 0xaa, 0xe1, 0x07, 0xe4, 0x9b, 0x52, 0xa6, 0x6a, 0x49, 0x9a, 0x2e,
	0x7c, 0x3d, 0xe1, 0x67, 0xe8, 0x56, 0x8a, 0x8c, 0x3c, 0x76, 0xe2, 0xe1, 0x13, 0x77, 0x51, 0xd3,
	0x6a, 0x26, 0x96, 0xa0, 0x49, 0xe0, 0x7a, 0x79, 0xb8, 0xe8, 0x65, 0x52, 0x6d, 0xe9, 0x11, 0x3b,
	0x34, 0x93, 0x69, 0x60, 0x56, 0x69, 0x82, 0xaa, 0x66, 0xea, 0xf1, 0xdd, 0xdb, 0x1f, 0xbb, 0xd0,
	0xdb, 0xee, 0x42, 0xef, 0xd7, 0x2e, 0xf4, 0xbe, 0xef, 0xc3, 0xc6, 0x76, 0x1f, 0x36, 0x7e, 0xee,
	0xc3, 0xc6, 0xe7, 0x68, 0x2e, 0xec, 0x62, 0x9d, 0xc6, 0x99, 0x92, 0x49, 0x65, 0x9f, 0x50, 0x48,
	0x36, 0xee, 0x82, 0x6c, 0x59, 0x80, 0x49, 0x7d, 0x77, 0x37, 0xfd, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x64, 0x2d, 0x7e, 0xea, 0x81, 0x02, 0x00, 0x00,
}

func (m *MarketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MarketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MarketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MarketDataRequest != nil {
		{
			size, err := m.MarketDataRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMarketData(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.SessionID) > 0 {
		i -= len(m.SessionID)
		copy(dAtA[i:], m.SessionID)
		i = encodeVarintMarketData(dAtA, i, uint64(len(m.SessionID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MarketDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MarketDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MarketDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintMarketData(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x52
	}
	if m.Trailer != nil {
		{
			size, err := m.Trailer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMarketData(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Mic) > 0 {
		i -= len(m.Mic)
		copy(dAtA[i:], m.Mic)
		i = encodeVarintMarketData(dAtA, i, uint64(len(m.Mic)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Symbol) > 0 {
		i -= len(m.Symbol)
		copy(dAtA[i:], m.Symbol)
		i = encodeVarintMarketData(dAtA, i, uint64(len(m.Symbol)))
		i--
		dAtA[i] = 0x3a
	}
	if m.NoRelatedSym != 0 {
		i = encodeVarintMarketData(dAtA, i, uint64(m.NoRelatedSym))
		i--
		dAtA[i] = 0x30
	}
	if m.MdUpdateType != 0 {
		i = encodeVarintMarketData(dAtA, i, uint64(m.MdUpdateType))
		i--
		dAtA[i] = 0x28
	}
	if m.MarketDepth != 0 {
		i = encodeVarintMarketData(dAtA, i, uint64(m.MarketDepth))
		i--
		dAtA[i] = 0x20
	}
	if m.SubscriptionRequestType != 0 {
		i = encodeVarintMarketData(dAtA, i, uint64(m.SubscriptionRequestType))
		i--
		dAtA[i] = 0x18
	}
	if len(m.MdReqID) > 0 {
		i -= len(m.MdReqID)
		copy(dAtA[i:], m.MdReqID)
		i = encodeVarintMarketData(dAtA, i, uint64(len(m.MdReqID)))
		i--
		dAtA[i] = 0x12
	}
	if m.Header != nil {
		{
			size, err := m.Header.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMarketData(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMarketData(dAtA []byte, offset int, v uint64) int {
	offset -= sovMarketData(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MarketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SessionID)
	if l > 0 {
		n += 1 + l + sovMarketData(uint64(l))
	}
	if m.MarketDataRequest != nil {
		l = m.MarketDataRequest.Size()
		n += 1 + l + sovMarketData(uint64(l))
	}
	return n
}

func (m *MarketDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Header != nil {
		l = m.Header.Size()
		n += 1 + l + sovMarketData(uint64(l))
	}
	l = len(m.MdReqID)
	if l > 0 {
		n += 1 + l + sovMarketData(uint64(l))
	}
	if m.SubscriptionRequestType != 0 {
		n += 1 + sovMarketData(uint64(m.SubscriptionRequestType))
	}
	if m.MarketDepth != 0 {
		n += 1 + sovMarketData(uint64(m.MarketDepth))
	}
	if m.MdUpdateType != 0 {
		n += 1 + sovMarketData(uint64(m.MdUpdateType))
	}
	if m.NoRelatedSym != 0 {
		n += 1 + sovMarketData(uint64(m.NoRelatedSym))
	}
	l = len(m.Symbol)
	if l > 0 {
		n += 1 + l + sovMarketData(uint64(l))
	}
	l = len(m.Mic)
	if l > 0 {
		n += 1 + l + sovMarketData(uint64(l))
	}
	if m.Trailer != nil {
		l = m.Trailer.Size()
		n += 1 + l + sovMarketData(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovMarketData(uint64(l))
	}
	return n
}

func sovMarketData(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMarketData(x uint64) (n int) {
	return sovMarketData(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MarketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMarketData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MarketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MarketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarketData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarketData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SessionID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketDataRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMarketData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMarketData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MarketDataRequest == nil {
				m.MarketDataRequest = &MarketDataRequest{}
			}
			if err := m.MarketDataRequest.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMarketData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMarketData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MarketDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMarketData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MarketDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MarketDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMarketData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMarketData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header == nil {
				m.Header = &Header{}
			}
			if err := m.Header.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MdReqID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarketData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarketData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MdReqID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubscriptionRequestType", wireType)
			}
			m.SubscriptionRequestType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubscriptionRequestType |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketDepth", wireType)
			}
			m.MarketDepth = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MarketDepth |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MdUpdateType", wireType)
			}
			m.MdUpdateType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MdUpdateType |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NoRelatedSym", wireType)
			}
			m.NoRelatedSym = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NoRelatedSym |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Symbol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarketData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarketData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Symbol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mic", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarketData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarketData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mic = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Trailer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMarketData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMarketData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Trailer == nil {
				m.Trailer = &Trailer{}
			}
			if err := m.Trailer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarketData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarketData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMarketData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMarketData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMarketData(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMarketData
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMarketData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMarketData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMarketData
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMarketData
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMarketData
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMarketData        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMarketData          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMarketData = fmt.Errorf("proto: unexpected end of group")
)
