// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: re/fix/orders_cancel_reject.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type OrdersCancelReject struct {
	// A string field that specifies the FIX session ID for the message.
	SessionID string `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	// A Header field that contains standard header information for the message,
	// such as the message type, sender and receiver identification, and sequence
	// number.
	Header *Header `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	// A string field that contains the ID of the order that was rejected. When an
	// order is submitted to a trading venue or OMS, it assigns a unique orderID
	// to that order to track and identify it within its system. If the order is
	// subsequently rejected, the trading venue or OMS would typically provide the
	// orderID associated with the rejected order in the OrdersCancelReject
	// message
	OrderID string `protobuf:"bytes,3,opt,name=orderID,proto3" json:"orderID,omitempty"`
	// A string field that contains the original client order ID for the order
	// that was cancelled.
	OrigClOrdID string `protobuf:"bytes,4,opt,name=origClOrdID,proto3" json:"origClOrdID,omitempty"`
	// A string field that contains the client order ID for the order that was
	// cancelled or modified.
	ClOrdID string `protobuf:"bytes,5,opt,name=clOrdID,proto3" json:"clOrdID,omitempty"`
	// An integer field that specifies the reason for the order cancellation
	// rejection, using a standard set of values defined in the FIX protocol.
	// Typically, the cxlRejReason field provides a numerical code or value that
	// represents a specific reason for the order cancellation rejection. Examples
	// of common cxlRejReason values in the FIX protocol include:
	//  0: Too Late to Cancel
	//  1: Unknown Order
	//  2: Broker/Exchange Option
	//  3: Order Already in Pending Cancel or Pending Replace Status
	//  4: Unable to Process Request
	//  5: Duplicate ClOrdID
	//  6: Unsupported Order Characteristic
	//  7: Other
	CxlRejReason int64 `protobuf:"varint,6,opt,name=cxlRejReason,proto3" json:"cxlRejReason,omitempty"`
	// An integer field that specifies the message sequence number of the order
	// cancellation request to which this message is responding. When an order
	// cancellation request is submitted, it is assigned a unique message sequence
	// number by the FIX engine or the trading system. This sequence number is
	// used to track and identify specific messages within the order flow. The
	// cxlRejResponseTo field in the OrdersCancelReject message is populated with
	// the sequence number of the original order cancellation request message that
	// resulted in the rejection.
	CxlRejResponseTo int64 `protobuf:"varint,7,opt,name=cxlRejResponseTo,proto3" json:"cxlRejResponseTo,omitempty"`
	// A string field that specifies the time of the transaction.
	TransactTime string `protobuf:"bytes,8,opt,name=transactTime,proto3" json:"transactTime,omitempty"`
	// A Trailer field that contains standard trailer information for the message,
	// such as the message checksum.
	Trailer *Trailer `protobuf:"bytes,9,opt,name=trailer,proto3" json:"trailer,omitempty"`
}

func (m *OrdersCancelReject) Reset()         { *m = OrdersCancelReject{} }
func (m *OrdersCancelReject) String() string { return proto.CompactTextString(m) }
func (*OrdersCancelReject) ProtoMessage()    {}
func (*OrdersCancelReject) Descriptor() ([]byte, []int) {
	return fileDescriptor_5581ec5cd57438b0, []int{0}
}
func (m *OrdersCancelReject) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OrdersCancelReject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OrdersCancelReject.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OrdersCancelReject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrdersCancelReject.Merge(m, src)
}
func (m *OrdersCancelReject) XXX_Size() int {
	return m.Size()
}
func (m *OrdersCancelReject) XXX_DiscardUnknown() {
	xxx_messageInfo_OrdersCancelReject.DiscardUnknown(m)
}

var xxx_messageInfo_OrdersCancelReject proto.InternalMessageInfo

func (m *OrdersCancelReject) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *OrdersCancelReject) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *OrdersCancelReject) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *OrdersCancelReject) GetOrigClOrdID() string {
	if m != nil {
		return m.OrigClOrdID
	}
	return ""
}

func (m *OrdersCancelReject) GetClOrdID() string {
	if m != nil {
		return m.ClOrdID
	}
	return ""
}

func (m *OrdersCancelReject) GetCxlRejReason() int64 {
	if m != nil {
		return m.CxlRejReason
	}
	return 0
}

func (m *OrdersCancelReject) GetCxlRejResponseTo() int64 {
	if m != nil {
		return m.CxlRejResponseTo
	}
	return 0
}

func (m *OrdersCancelReject) GetTransactTime() string {
	if m != nil {
		return m.TransactTime
	}
	return ""
}

func (m *OrdersCancelReject) GetTrailer() *Trailer {
	if m != nil {
		return m.Trailer
	}
	return nil
}

func init() {
	proto.RegisterType((*OrdersCancelReject)(nil), "jim380.re.fix.OrdersCancelReject")
}

func init() { proto.RegisterFile("re/fix/orders_cancel_reject.proto", fileDescriptor_5581ec5cd57438b0) }

var fileDescriptor_5581ec5cd57438b0 = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x41, 0x4b, 0x02, 0x41,
	0x14, 0xc7, 0x5d, 0x2d, 0xcd, 0xb1, 0x20, 0x06, 0x8a, 0x21, 0x6a, 0xd9, 0x3c, 0x49, 0xd0, 0xae,
	0xe4, 0x25, 0x3a, 0xa6, 0x87, 0x3c, 0x09, 0x83, 0xa7, 0x2e, 0x32, 0xce, 0x3e, 0x75, 0xc4, 0xdd,
	0x91, 0x37, 0x13, 0x6c, 0xdf, 0xa2, 0x8f, 0xd5, 0xd1, 0x63, 0x97, 0x20, 0xf4, 0x8b, 0x84, 0xb3,
	0x2b, 0x65, 0x1d, 0xdf, 0xff, 0xff, 0x7f, 0xbf, 0xf7, 0x1e, 0x8f, 0x5c, 0x23, 0x44, 0x13, 0x95,
	0x45, 0x1a, 0x63, 0x40, 0x33, 0x92, 0x22, 0x95, 0xb0, 0x18, 0x21, 0xcc, 0x41, 0xda, 0x70, 0x89,
	0xda, 0x6a, 0x7a, 0x32, 0x57, 0x49, 0xe7, 0xbe, 0x1d, 0x22, 0x84, 0x13, 0x95, 0x5d, 0x5c, 0x15,
	0x1d, 0xc6, 0x8a, 0x34, 0x16, 0x18, 0x8f, 0x12, 0x30, 0x46, 0x4c, 0x21, 0x4f, 0x37, 0x3f, 0xcb,
	0x84, 0x0e, 0x1c, 0xac, 0xeb, 0x58, 0xdc, 0xa1, 0xe8, 0x25, 0xa9, 0x1b, 0x30, 0x46, 0xe9, 0xb4,
	0xdf, 0x63, 0x5e, 0xe0, 0xb5, 0xea, 0xfc, 0x47, 0xa0, 0xb7, 0xa4, 0x3a, 0x03, 0x11, 0x03, 0xb2,
	0x72, 0xe0, 0xb5, 0x1a, 0x77, 0x67, 0xe1, 0xde, 0xcc, 0xf0, 0xc9, 0x99, 0xbc, 0x08, 0x51, 0x46,
	0x6a, 0x6e, 0xdf, 0x7e, 0x8f, 0x55, 0x1c, 0x6a, 0x57, 0xd2, 0x80, 0x34, 0x34, 0xaa, 0x69, 0x77,
	0x31, 0xc0, 0xb8, 0xdf, 0x63, 0x07, 0xce, 0xfd, 0x2d, 0x6d, 0x7b, 0x65, 0xe1, 0x1e, 0xe6, 0xbd,
	0x45, 0x49, 0x9b, 0xe4, 0x58, 0x66, 0xdb, 0x7d, 0x39, 0x08, 0xa3, 0x53, 0x56, 0x0d, 0xbc, 0x56,
	0x85, 0xef, 0x69, 0xf4, 0x86, 0x9c, 0xee, 0x6a, 0xb3, 0xd4, 0xa9, 0x81, 0xa1, 0x66, 0x35, 0x97,
	0xfb, 0xa7, 0x6f, 0x79, 0x16, 0x45, 0x6a, 0x84, 0xb4, 0x43, 0x95, 0x00, 0x3b, 0x72, 0xe3, 0xf6,
	0x34, 0xda, 0x26, 0x35, 0x8b, 0x42, 0x2d, 0x00, 0x59, 0xdd, 0x5d, 0x7e, 0xfe, 0xe7, 0xf2, 0x61,
	0xee, 0xf2, 0x5d, 0xec, 0xf1, 0xe1, 0x7d, 0xed, 0x7b, 0xab, 0xb5, 0xef, 0x7d, 0xad, 0x7d, 0xef,
	0x6d, 0xe3, 0x97, 0x56, 0x1b, 0xbf, 0xf4, 0xb1, 0xf1, 0x4b, 0xcf, 0xc1, 0x54, 0xd9, 0xd9, 0xcb,
	0x38, 0x94, 0x3a, 0x89, 0x72, 0x48, 0xc4, 0x21, 0xca, 0xdc, 0xb3, 0xec, 0xeb, 0x12, 0xcc, 0xb8,
	0xea, 0x5e, 0xd4, 0xf9, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x1e, 0xe9, 0xc3, 0xc2, 0xf5, 0x01, 0x00,
	0x00,
}

func (m *OrdersCancelReject) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OrdersCancelReject) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OrdersCancelReject) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Trailer != nil {
		{
			size, err := m.Trailer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOrdersCancelReject(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if len(m.TransactTime) > 0 {
		i -= len(m.TransactTime)
		copy(dAtA[i:], m.TransactTime)
		i = encodeVarintOrdersCancelReject(dAtA, i, uint64(len(m.TransactTime)))
		i--
		dAtA[i] = 0x42
	}
	if m.CxlRejResponseTo != 0 {
		i = encodeVarintOrdersCancelReject(dAtA, i, uint64(m.CxlRejResponseTo))
		i--
		dAtA[i] = 0x38
	}
	if m.CxlRejReason != 0 {
		i = encodeVarintOrdersCancelReject(dAtA, i, uint64(m.CxlRejReason))
		i--
		dAtA[i] = 0x30
	}
	if len(m.ClOrdID) > 0 {
		i -= len(m.ClOrdID)
		copy(dAtA[i:], m.ClOrdID)
		i = encodeVarintOrdersCancelReject(dAtA, i, uint64(len(m.ClOrdID)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.OrigClOrdID) > 0 {
		i -= len(m.OrigClOrdID)
		copy(dAtA[i:], m.OrigClOrdID)
		i = encodeVarintOrdersCancelReject(dAtA, i, uint64(len(m.OrigClOrdID)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.OrderID) > 0 {
		i -= len(m.OrderID)
		copy(dAtA[i:], m.OrderID)
		i = encodeVarintOrdersCancelReject(dAtA, i, uint64(len(m.OrderID)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Header != nil {
		{
			size, err := m.Header.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOrdersCancelReject(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.SessionID) > 0 {
		i -= len(m.SessionID)
		copy(dAtA[i:], m.SessionID)
		i = encodeVarintOrdersCancelReject(dAtA, i, uint64(len(m.SessionID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintOrdersCancelReject(dAtA []byte, offset int, v uint64) int {
	offset -= sovOrdersCancelReject(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OrdersCancelReject) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SessionID)
	if l > 0 {
		n += 1 + l + sovOrdersCancelReject(uint64(l))
	}
	if m.Header != nil {
		l = m.Header.Size()
		n += 1 + l + sovOrdersCancelReject(uint64(l))
	}
	l = len(m.OrderID)
	if l > 0 {
		n += 1 + l + sovOrdersCancelReject(uint64(l))
	}
	l = len(m.OrigClOrdID)
	if l > 0 {
		n += 1 + l + sovOrdersCancelReject(uint64(l))
	}
	l = len(m.ClOrdID)
	if l > 0 {
		n += 1 + l + sovOrdersCancelReject(uint64(l))
	}
	if m.CxlRejReason != 0 {
		n += 1 + sovOrdersCancelReject(uint64(m.CxlRejReason))
	}
	if m.CxlRejResponseTo != 0 {
		n += 1 + sovOrdersCancelReject(uint64(m.CxlRejResponseTo))
	}
	l = len(m.TransactTime)
	if l > 0 {
		n += 1 + l + sovOrdersCancelReject(uint64(l))
	}
	if m.Trailer != nil {
		l = m.Trailer.Size()
		n += 1 + l + sovOrdersCancelReject(uint64(l))
	}
	return n
}

func sovOrdersCancelReject(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOrdersCancelReject(x uint64) (n int) {
	return sovOrdersCancelReject(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *OrdersCancelReject) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrdersCancelReject
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OrdersCancelReject: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OrdersCancelReject: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrdersCancelReject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrdersCancelReject
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOrdersCancelReject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SessionID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrdersCancelReject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrdersCancelReject
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOrdersCancelReject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header == nil {
				m.Header = &Header{}
			}
			if err := m.Header.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrdersCancelReject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrdersCancelReject
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOrdersCancelReject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrigClOrdID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrdersCancelReject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrdersCancelReject
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOrdersCancelReject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrigClOrdID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClOrdID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrdersCancelReject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrdersCancelReject
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOrdersCancelReject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClOrdID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CxlRejReason", wireType)
			}
			m.CxlRejReason = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrdersCancelReject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CxlRejReason |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CxlRejResponseTo", wireType)
			}
			m.CxlRejResponseTo = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrdersCancelReject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CxlRejResponseTo |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransactTime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrdersCancelReject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrdersCancelReject
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOrdersCancelReject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransactTime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Trailer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrdersCancelReject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrdersCancelReject
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOrdersCancelReject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Trailer == nil {
				m.Trailer = &Trailer{}
			}
			if err := m.Trailer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOrdersCancelReject(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOrdersCancelReject
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOrdersCancelReject(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOrdersCancelReject
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOrdersCancelReject
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOrdersCancelReject
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthOrdersCancelReject
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupOrdersCancelReject
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthOrdersCancelReject
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthOrdersCancelReject        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOrdersCancelReject          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupOrdersCancelReject = fmt.Errorf("proto: unexpected end of group")
)
