// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: re/fix/sessions.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Sessions struct {
	SessionName      string          `protobuf:"bytes,1,opt,name=sessionName,proto3" json:"sessionName,omitempty"`
	LogonInitiator   *LogonInitiator `protobuf:"bytes,2,opt,name=logonInitiator,proto3" json:"logonInitiator,omitempty"`
	InitiatorAddress string          `protobuf:"bytes,3,opt,name=initiatorAddress,proto3" json:"initiatorAddress,omitempty"`
	LogonAcceptor    *LogonAcceptor  `protobuf:"bytes,4,opt,name=logonAcceptor,proto3" json:"logonAcceptor,omitempty"`
	AcceptorAddress  string          `protobuf:"bytes,5,opt,name=acceptorAddress,proto3" json:"acceptorAddress,omitempty"`
	IsLoggedIn       bool            `protobuf:"varint,6,opt,name=IsLoggedIn,proto3" json:"IsLoggedIn,omitempty"`
	IsAccepted       bool            `protobuf:"varint,7,opt,name=IsAccepted,proto3" json:"IsAccepted,omitempty"`
}

func (m *Sessions) Reset()         { *m = Sessions{} }
func (m *Sessions) String() string { return proto.CompactTextString(m) }
func (*Sessions) ProtoMessage()    {}
func (*Sessions) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d4d646ca64d70e3, []int{0}
}
func (m *Sessions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Sessions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Sessions.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Sessions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sessions.Merge(m, src)
}
func (m *Sessions) XXX_Size() int {
	return m.Size()
}
func (m *Sessions) XXX_DiscardUnknown() {
	xxx_messageInfo_Sessions.DiscardUnknown(m)
}

var xxx_messageInfo_Sessions proto.InternalMessageInfo

func (m *Sessions) GetSessionName() string {
	if m != nil {
		return m.SessionName
	}
	return ""
}

func (m *Sessions) GetLogonInitiator() *LogonInitiator {
	if m != nil {
		return m.LogonInitiator
	}
	return nil
}

func (m *Sessions) GetInitiatorAddress() string {
	if m != nil {
		return m.InitiatorAddress
	}
	return ""
}

func (m *Sessions) GetLogonAcceptor() *LogonAcceptor {
	if m != nil {
		return m.LogonAcceptor
	}
	return nil
}

func (m *Sessions) GetAcceptorAddress() string {
	if m != nil {
		return m.AcceptorAddress
	}
	return ""
}

func (m *Sessions) GetIsLoggedIn() bool {
	if m != nil {
		return m.IsLoggedIn
	}
	return false
}

func (m *Sessions) GetIsAccepted() bool {
	if m != nil {
		return m.IsAccepted
	}
	return false
}

type LogonInitiator struct {
	Header        *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	EncryptMethod int64    `protobuf:"varint,2,opt,name=encryptMethod,proto3" json:"encryptMethod,omitempty"`
	HeartBtInt    int64    `protobuf:"varint,3,opt,name=heartBtInt,proto3" json:"heartBtInt,omitempty"`
	Trailer       *Trailer `protobuf:"bytes,4,opt,name=trailer,proto3" json:"trailer,omitempty"`
}

func (m *LogonInitiator) Reset()         { *m = LogonInitiator{} }
func (m *LogonInitiator) String() string { return proto.CompactTextString(m) }
func (*LogonInitiator) ProtoMessage()    {}
func (*LogonInitiator) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d4d646ca64d70e3, []int{1}
}
func (m *LogonInitiator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LogonInitiator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LogonInitiator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LogonInitiator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogonInitiator.Merge(m, src)
}
func (m *LogonInitiator) XXX_Size() int {
	return m.Size()
}
func (m *LogonInitiator) XXX_DiscardUnknown() {
	xxx_messageInfo_LogonInitiator.DiscardUnknown(m)
}

var xxx_messageInfo_LogonInitiator proto.InternalMessageInfo

func (m *LogonInitiator) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *LogonInitiator) GetEncryptMethod() int64 {
	if m != nil {
		return m.EncryptMethod
	}
	return 0
}

func (m *LogonInitiator) GetHeartBtInt() int64 {
	if m != nil {
		return m.HeartBtInt
	}
	return 0
}

func (m *LogonInitiator) GetTrailer() *Trailer {
	if m != nil {
		return m.Trailer
	}
	return nil
}

type LogonAcceptor struct {
	Header        *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	EncryptMethod int64    `protobuf:"varint,2,opt,name=encryptMethod,proto3" json:"encryptMethod,omitempty"`
	HeartBtInt    int64    `protobuf:"varint,3,opt,name=heartBtInt,proto3" json:"heartBtInt,omitempty"`
	Trailer       *Trailer `protobuf:"bytes,4,opt,name=trailer,proto3" json:"trailer,omitempty"`
}

func (m *LogonAcceptor) Reset()         { *m = LogonAcceptor{} }
func (m *LogonAcceptor) String() string { return proto.CompactTextString(m) }
func (*LogonAcceptor) ProtoMessage()    {}
func (*LogonAcceptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d4d646ca64d70e3, []int{2}
}
func (m *LogonAcceptor) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LogonAcceptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LogonAcceptor.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LogonAcceptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogonAcceptor.Merge(m, src)
}
func (m *LogonAcceptor) XXX_Size() int {
	return m.Size()
}
func (m *LogonAcceptor) XXX_DiscardUnknown() {
	xxx_messageInfo_LogonAcceptor.DiscardUnknown(m)
}

var xxx_messageInfo_LogonAcceptor proto.InternalMessageInfo

func (m *LogonAcceptor) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *LogonAcceptor) GetEncryptMethod() int64 {
	if m != nil {
		return m.EncryptMethod
	}
	return 0
}

func (m *LogonAcceptor) GetHeartBtInt() int64 {
	if m != nil {
		return m.HeartBtInt
	}
	return 0
}

func (m *LogonAcceptor) GetTrailer() *Trailer {
	if m != nil {
		return m.Trailer
	}
	return nil
}

func init() {
	proto.RegisterType((*Sessions)(nil), "jim380.re.fix.Sessions")
	proto.RegisterType((*LogonInitiator)(nil), "jim380.re.fix.LogonInitiator")
	proto.RegisterType((*LogonAcceptor)(nil), "jim380.re.fix.LogonAcceptor")
}

func init() { proto.RegisterFile("re/fix/sessions.proto", fileDescriptor_7d4d646ca64d70e3) }

var fileDescriptor_7d4d646ca64d70e3 = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x93, 0xc1, 0xaa, 0xd3, 0x40,
	0x14, 0x86, 0x3b, 0xb7, 0xda, 0x7b, 0x9d, 0x92, 0xab, 0x0c, 0x5c, 0x09, 0xe2, 0x0d, 0xa1, 0xb8,
	0x08, 0x82, 0xc9, 0xa5, 0xdd, 0x88, 0xbb, 0x16, 0x04, 0x03, 0xd5, 0xc5, 0xe8, 0xca, 0x8d, 0x4c,
	0x33, 0xa7, 0xc9, 0x48, 0x93, 0x09, 0x33, 0x23, 0xb4, 0x6f, 0xe1, 0xd3, 0xe8, 0x2b, 0xb8, 0x11,
	0xba, 0x74, 0x29, 0xed, 0x8b, 0x48, 0x27, 0x19, 0x68, 0xa2, 0x2f, 0xe0, 0x2e, 0xf9, 0xcf, 0x7f,
	0xce, 0x77, 0xe6, 0x87, 0x83, 0x6f, 0x14, 0x24, 0x6b, 0xb1, 0x4d, 0x34, 0x68, 0x2d, 0x64, 0xa5,
	0xe3, 0x5a, 0x49, 0x23, 0x89, 0xf7, 0x59, 0x94, 0xb3, 0x97, 0x77, 0xb1, 0x82, 0x78, 0x2d, 0xb6,
	0x4f, 0x6e, 0x9d, 0xcb, 0xb0, 0x8a, 0x33, 0xc5, 0x3f, 0x95, 0xa0, 0x35, 0xcb, 0xa1, 0x71, 0x4f,
	0x7e, 0x5e, 0xe0, 0xab, 0xf7, 0xed, 0x00, 0x12, 0xe2, 0x71, 0x3b, 0xec, 0x1d, 0x2b, 0xc1, 0x47,
	0x21, 0x8a, 0x1e, 0xd0, 0x73, 0x89, 0xbc, 0xc6, 0xd7, 0x1b, 0x99, 0xcb, 0x2a, 0xad, 0x84, 0x11,
	0xcc, 0x48, 0xe5, 0x5f, 0x84, 0x28, 0x1a, 0x4f, 0x6f, 0xe3, 0x0e, 0x35, 0x5e, 0x76, 0x4c, 0xb4,
	0xd7, 0x44, 0x9e, 0xe3, 0x47, 0xc2, 0xfd, 0xcc, 0x39, 0x57, 0xa0, 0xb5, 0x3f, 0xb4, 0xb4, 0xbf,
	0x74, 0xb2, 0xc0, 0x9e, 0xed, 0x9e, 0x67, 0x19, 0xd4, 0x27, 0xe2, 0x3d, 0x4b, 0x7c, 0xfa, 0x2f,
	0xa2, 0xf3, 0xd0, 0x6e, 0x0b, 0x89, 0xf0, 0x43, 0xd6, 0x7e, 0x3b, 0xdc, 0x7d, 0x8b, 0xeb, 0xcb,
	0x24, 0xc0, 0x38, 0xd5, 0x4b, 0x99, 0xe7, 0xc0, 0xd3, 0xca, 0x1f, 0x85, 0x28, 0xba, 0xa2, 0x67,
	0x4a, 0x53, 0x6f, 0xe6, 0x02, 0xf7, 0x2f, 0x5d, 0xdd, 0x29, 0x93, 0xef, 0x08, 0x5f, 0x77, 0x1f,
	0x4f, 0x5e, 0xe0, 0x51, 0x01, 0x8c, 0x83, 0xb2, 0x81, 0x8e, 0xa7, 0x37, 0xbd, 0xcd, 0xdf, 0xd8,
	0x22, 0x6d, 0x4d, 0xe4, 0x19, 0xf6, 0xa0, 0xca, 0xd4, 0xae, 0x36, 0x6f, 0xc1, 0x14, 0x92, 0xdb,
	0x84, 0x87, 0xb4, 0x2b, 0x9e, 0xf6, 0x28, 0x80, 0x29, 0xb3, 0x30, 0x69, 0x65, 0x6c, 0x76, 0x43,
	0x7a, 0xa6, 0x90, 0x3b, 0x7c, 0x69, 0x14, 0x13, 0x1b, 0x70, 0x79, 0x3d, 0xee, 0x51, 0x3f, 0x34,
	0x55, 0xea, 0x6c, 0x93, 0x6f, 0x08, 0x7b, 0x9d, 0x10, 0xff, 0x93, 0xc5, 0x17, 0xaf, 0x7e, 0x1c,
	0x02, 0xb4, 0x3f, 0x04, 0xe8, 0xf7, 0x21, 0x40, 0x5f, 0x8f, 0xc1, 0x60, 0x7f, 0x0c, 0x06, 0xbf,
	0x8e, 0xc1, 0xe0, 0x63, 0x98, 0x0b, 0x53, 0x7c, 0x59, 0xc5, 0x99, 0x2c, 0x93, 0x66, 0x48, 0x42,
	0x21, 0xd9, 0xda, 0x7b, 0x30, 0xbb, 0x1a, 0xf4, 0x6a, 0x64, 0xaf, 0x60, 0xf6, 0x27, 0x00, 0x00,
	0xff, 0xff, 0x4f, 0x6c, 0x87, 0xbd, 0x4c, 0x03, 0x00, 0x00,
}

func (m *Sessions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Sessions) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Sessions) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsAccepted {
		i--
		if m.IsAccepted {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.IsLoggedIn {
		i--
		if m.IsLoggedIn {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if len(m.AcceptorAddress) > 0 {
		i -= len(m.AcceptorAddress)
		copy(dAtA[i:], m.AcceptorAddress)
		i = encodeVarintSessions(dAtA, i, uint64(len(m.AcceptorAddress)))
		i--
		dAtA[i] = 0x2a
	}
	if m.LogonAcceptor != nil {
		{
			size, err := m.LogonAcceptor.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSessions(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.InitiatorAddress) > 0 {
		i -= len(m.InitiatorAddress)
		copy(dAtA[i:], m.InitiatorAddress)
		i = encodeVarintSessions(dAtA, i, uint64(len(m.InitiatorAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if m.LogonInitiator != nil {
		{
			size, err := m.LogonInitiator.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSessions(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.SessionName) > 0 {
		i -= len(m.SessionName)
		copy(dAtA[i:], m.SessionName)
		i = encodeVarintSessions(dAtA, i, uint64(len(m.SessionName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LogonInitiator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LogonInitiator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LogonInitiator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Trailer != nil {
		{
			size, err := m.Trailer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSessions(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.HeartBtInt != 0 {
		i = encodeVarintSessions(dAtA, i, uint64(m.HeartBtInt))
		i--
		dAtA[i] = 0x18
	}
	if m.EncryptMethod != 0 {
		i = encodeVarintSessions(dAtA, i, uint64(m.EncryptMethod))
		i--
		dAtA[i] = 0x10
	}
	if m.Header != nil {
		{
			size, err := m.Header.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSessions(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LogonAcceptor) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LogonAcceptor) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LogonAcceptor) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Trailer != nil {
		{
			size, err := m.Trailer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSessions(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.HeartBtInt != 0 {
		i = encodeVarintSessions(dAtA, i, uint64(m.HeartBtInt))
		i--
		dAtA[i] = 0x18
	}
	if m.EncryptMethod != 0 {
		i = encodeVarintSessions(dAtA, i, uint64(m.EncryptMethod))
		i--
		dAtA[i] = 0x10
	}
	if m.Header != nil {
		{
			size, err := m.Header.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSessions(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSessions(dAtA []byte, offset int, v uint64) int {
	offset -= sovSessions(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Sessions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SessionName)
	if l > 0 {
		n += 1 + l + sovSessions(uint64(l))
	}
	if m.LogonInitiator != nil {
		l = m.LogonInitiator.Size()
		n += 1 + l + sovSessions(uint64(l))
	}
	l = len(m.InitiatorAddress)
	if l > 0 {
		n += 1 + l + sovSessions(uint64(l))
	}
	if m.LogonAcceptor != nil {
		l = m.LogonAcceptor.Size()
		n += 1 + l + sovSessions(uint64(l))
	}
	l = len(m.AcceptorAddress)
	if l > 0 {
		n += 1 + l + sovSessions(uint64(l))
	}
	if m.IsLoggedIn {
		n += 2
	}
	if m.IsAccepted {
		n += 2
	}
	return n
}

func (m *LogonInitiator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Header != nil {
		l = m.Header.Size()
		n += 1 + l + sovSessions(uint64(l))
	}
	if m.EncryptMethod != 0 {
		n += 1 + sovSessions(uint64(m.EncryptMethod))
	}
	if m.HeartBtInt != 0 {
		n += 1 + sovSessions(uint64(m.HeartBtInt))
	}
	if m.Trailer != nil {
		l = m.Trailer.Size()
		n += 1 + l + sovSessions(uint64(l))
	}
	return n
}

func (m *LogonAcceptor) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Header != nil {
		l = m.Header.Size()
		n += 1 + l + sovSessions(uint64(l))
	}
	if m.EncryptMethod != 0 {
		n += 1 + sovSessions(uint64(m.EncryptMethod))
	}
	if m.HeartBtInt != 0 {
		n += 1 + sovSessions(uint64(m.HeartBtInt))
	}
	if m.Trailer != nil {
		l = m.Trailer.Size()
		n += 1 + l + sovSessions(uint64(l))
	}
	return n
}

func sovSessions(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSessions(x uint64) (n int) {
	return sovSessions(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Sessions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSessions
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Sessions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Sessions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSessions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSessions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SessionName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogonInitiator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessions
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LogonInitiator == nil {
				m.LogonInitiator = &LogonInitiator{}
			}
			if err := m.LogonInitiator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitiatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSessions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSessions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InitiatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogonAcceptor", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessions
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LogonAcceptor == nil {
				m.LogonAcceptor = &LogonAcceptor{}
			}
			if err := m.LogonAcceptor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcceptorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSessions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSessions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AcceptorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsLoggedIn", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsLoggedIn = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsAccepted", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsAccepted = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipSessions(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSessions
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LogonInitiator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSessions
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LogonInitiator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LogonInitiator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessions
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header == nil {
				m.Header = &Header{}
			}
			if err := m.Header.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptMethod", wireType)
			}
			m.EncryptMethod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EncryptMethod |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeartBtInt", wireType)
			}
			m.HeartBtInt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HeartBtInt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Trailer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessions
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Trailer == nil {
				m.Trailer = &Trailer{}
			}
			if err := m.Trailer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSessions(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSessions
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LogonAcceptor) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSessions
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LogonAcceptor: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LogonAcceptor: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessions
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header == nil {
				m.Header = &Header{}
			}
			if err := m.Header.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptMethod", wireType)
			}
			m.EncryptMethod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EncryptMethod |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeartBtInt", wireType)
			}
			m.HeartBtInt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HeartBtInt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Trailer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessions
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Trailer == nil {
				m.Trailer = &Trailer{}
			}
			if err := m.Trailer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSessions(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSessions
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSessions(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSessions
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSessions
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSessions
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSessions
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSessions
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSessions
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSessions        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSessions          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSessions = fmt.Errorf("proto: unexpected end of group")
)
